### Network ###
- platform: pi_hole
  host: localhost:4865
  location: ""
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - dns_queries_today
        
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use
    - type: memory_free
    - type: processor_use
    - type: last_boot
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: ipv4_address
      arg: eth0
    - type: load_1m
    - type: load_5m
    - type: load_15m
    
- platform: template
  sensors:
    living_motion_all:
      friendly_name: "Living Room Motion"
      icon_template: >-
        {% if is_state('binary_sensor.living_room_motion_motion', 'on') %}
          mdi:run
        {% else %}
          mdi:walk
        {% endif %}
      value_template: >-
        {% if is_state('binary_sensor.living_room_motion_motion', 'on') %}
          active
        {% else %}
          inactive
        {% endif %}
- platform: template
  sensors:
    bedroom_motion_all:
      friendly_name: "Bedroom Motion All"
      icon_template: >-
        {% if is_state('binary_sensor.bedroom_motion_motion', 'on') or is_state('binary_sensor.bedroom_multi_sensor_motion', 'on') %}
          mdi:run
        {% else %}
          mdi:walk
        {% endif %}
      value_template: >-
        {% if is_state('binary_sensor.bedroom_motion_motion', 'on') or is_state('binary_sensor.bedroom_multi_sensor_motion', 'on') %}
          active
        {% else %}
          inactive
        {% endif %}
- platform: template
  sensors:
    bathroom_motion_all:
      friendly_name: "Bathroom Motion All"
      icon_template: >-
        {% if is_state('binary_sensor.bathroom_motion_motion', 'on') or is_state('binary_sensor.shower_motion_motion', 'on') %}
          mdi:run
        {% else %}
          mdi:walk
        {% endif %}
      value_template: >-
        {% if is_state('binary_sensor.bathroom_motion_motion', 'on') or is_state('binary_sensor.shower_motion_motion', 'on') %}
          active
        {% else %}
          inactive
        {% endif %}
- platform: template
  sensors:
    litter_box:
      value_template: >-
        {% if states.binary_sensor.litter_box_2_contact_2.state == 'on' %}
          Open
        {% elif states.binary_sensor.litter_box_2_contact_2.state == 'off' %}
          Closed
        {% else %}
          Failed
        {% endif %}
      icon_template: >-
        {% if states.binary_sensor.litter_box_2_contact_2.state == 'on' %}
          mdi:delete
        {% elif states.binary_sensor.litter_box_2_contact_2.state == 'off' %}
          mdi:cat
        {% endif %}
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'